POST http://localhost:3300/posts
Content-Type: application/json

{
    "title": "Post 1 testing post zzzzzzzzzzzzzzzzzzzz",
    "content": "Content 2",
    "postType": "post",
    "slug": "post-2",
    "status": "published",
    "schema": "{\r\n \"@context\": \"https://schema.org\",\r\n \"@type\": \"Person\"\r\n}",
    "featuredImageUrl": "http://string.com",
    "publishedOn": "2021-08-01T00:00:00.000Z",
    "tags": [1],
    "metaOptions":{
        "metaValue": "{\"sidebarEnbaled\": true, \"theme\": \"dark\"}"
    },
    "authorId": 1
}