PATCH http://localhost:3300/posts
Content-Type: application/json

{
        "id": 13,
        "title": "Post with tags update",
        "content": "Content 1 with tags",
        "postType": "post",
        "slug": "post-1",
        "status": "published",
        "featuredImageUrl": "http://string.com",
        "publishedOn": "2021-08-01T00:00:00.000Z",
        "tags": [1, 2]
}